---
title: "Studies"
editor: visual
editor_options: 
  chunk_output_type: console
---

### BioHUG has close links to many other Geneva research projects and researchers

By making and storing DNA samples in a cost efficient way, BioHUG supports many other Geneva based research projects and researchers. These include Prof. [Caroline Samer](https://www.hug.ch/pharmacologie-toxicologie-cliniques/pre-caroline-samer){target="_blank" rel="noopener noreferrer"} , who leads "Pharmacogenomic" studies of adverse drug reactions and why some medications do not work in some patients.

We also work closely with the [SIMED team](https://www.unige.ch/medecine/simed/){target="_blank" rel="noopener noreferrer"} including Dr [Mina Bjelogrlic](https://www.unige.ch/medecine/simed/en/simed-team/data-team/mina-bjelogrlic){target="_blank" rel="noopener noreferrer"} and Prof [Christian Lovis](https://www.unige.ch/medecine/simed/en/simed-team/management-and-administration/christian-lovis){target="_blank" rel="noopener noreferrer"} to enable researchers to work with measures of disease derived from medical records.

[CALIBRATE](../fr/study_calibrate.qmd) is a research project led by Dr [Aurelie Kamoun](https://www.unige.ch/medecine/gede/en/research-groups/timothy-frayling/group-members/aurelie-kamoun){target="_blank" rel="noopener noreferrer"}, Dr [Christophe Gaudet-Blavignac](https://www.unige.ch/medecine/simed/en/simed-team/data-team/christophe-gaudet-blavignac-phd){target="_blank" rel="noopener noreferrer"} and Prof. [Christian Lovis](https://www.unige.ch/medecine/simed/en/simed-team/management-and-administration/christian-lovis){target="_blank" rel="noopener noreferrer"}, that will test if and how routinely measured clinical biomarkers should be re-calibrated to more personalised reference ranges.
