project:
  type: website

website:
  site-url: https://CDGG-unige.github.io/biohugwebsite/
  repo-url: https://github.com/CDGG-unige/biohugwebsite/
  
  title: "BioHUG"
  navbar:
    left:
      - text: "For patients"
        menu:
          - text: "What is BioHUG?"
            href: patients/whatisbiohug.qmd
          - text: "BioHUG FAQ"
            href: patients/faqs.qmd
          - text: "BioHUG consent"
            href: patients/consent.qmd
          - text: "Use of BioHUG samples"
            href: patients/useofsamples.qmd
      - text: "For researchers"
        menu:
          - text: "BioHUG description"
            href: researchers/description.qmd
          - text: "How to use BioHUG"
            href: researchers/howtouse.qmd
  page-footer:
    center: "BioHUG — Hôpitaux Universitaires de Genève (HUG)"

format:
  html:
    theme:
      light:
        - flatly
        - custom.scss
    toc: true
