---
title: "The Team"
editor: visual
editor_options: 
  chunk_output_type: console
---

### Meet the team

BioHUG is lead by a group of researchers, clinicians and patients at the Faculty of Medicine, University of Geneva, and HUG. Prof Timothy Frayling and Dr Aurelie Kamoun of the [Common Disease Genetics and Genomics team](https://www.unige.ch/medecine/gede/groupes/timothy-frayling){target="_blank" rel="noopener noreferrer"} coordinate the study. Dr Marina LeRoy is our patient representative. The Fondation de HUG provide generous financial support. The [Genetic Medicine Division](https://www.hug.ch/medecine-genetique){target="_blank" rel="noopener noreferrer"} at HUG provides laboratory facilities and Mr Tiago De Sousa is our dedicated technician.

### BioHUG scientific and management committee

The BioHUG team are supported by a local scientific committee including Prof Marc Abramowicz, Profe. Valerie Schwitzgebel, Prof. Georg Ehret, Dr Thomas Rio Frio and Dr Julien Virzi.

### International scientific advisory committee

The BioHUG team are supported by representatives from similar Hospital Biobanks from around the world.

For more details on BioHUG governance see the [Governance](researchers/governance.qmd.qmd) page.
