---
title: "BioHUG governance"
editor: visual
---

# Approval of BioHUG

The HUG medical directorate, in 2023, approved plans to flag blood samples from HUG patients who had signed the general consent. In early 2024 the [CCER](https://www.ge.ch/ccer-obtenir-autorisation-recherche-medicale-etre-humain){target="_blank" rel="noopener noreferrer"} was consulted during the planning phase of the BioHUG biobank when they advised on the the process of Biobanking DNA samples at HUG.

# Canton de Geneve research ethics committee

[CCER](https://www.ge.ch/ccer-obtenir-autorisation-recherche-medicale-etre-humain){target="_blank" rel="noopener noreferrer"} applications are submitted with each update to BioHUG. As of March 2026, these updates include approval to link and prioritise samples from research studies and registries, and approval for the first project involving genetic data, "CALIBRATE".

# Swiss Biobanking platform

BioHUG has Swiss Biobanking Platform VITA status [Download PDF](../images/Certificat_VITA_BioHUG.pdf.pdf) that demonstrates our compliance with the standards of Swiss Biobanking of human samples. We also adhere to the advice of the Swiss Personalised Health Network, including their approach to [incidental findings](https://sphn.ch/wp-content/uploads/2020/05/Guidance_20200429_Reporting-actionable-genetic-findings_Final.pdf){target="_blank" rel="noopener noreferrer"}. We also follow closely the work of other biobanking projects, and their approach to data goverance and participant feedback, including [Genomics England](https://www.genomicsengland.co.uk/patients-participants/data){target="_blank" rel="noopener noreferrer"} and [Our Future Health](https://ourfuturehealth.org.uk/){target="_blank" rel="noopener noreferrer"}

# Local oversight

The BioHUG management board guides the oversight and activities of BioHUG. The local board consists of HUG clinicians, clinical scientists and a patient representative.

# Patient involvement

We involve patients in BioHUG by meeting regularly with the HUG [patients partenaires forum](https://www.hug.ch/patients-partenaires){target="_blank" rel="noopener noreferrer"}

# International SAB

Our ISAB consists of experts from other hospitals around the world who have similar biobanks including [BioVU](https://victr.vumc.org/what-is-biovu/){target="_blank" rel="noopener noreferrer"}, [BioME](https://www.nature.com/articles/d42473-022-00272-1){target="_blank" rel="noopener noreferrer"} and [SHARE](https://www.registerforshare.org/){target="_blank" rel="noopener noreferrer"}.

# Research projects

All researchers wising to use the samples or data originating from BioHUG must obtain specific ethics approval for their project from the [Canton de Geneve research ethics committee (CCER)](https://www.ge.ch/ccer-obtenir-autorisation-recherche-medicale-etre-humain){target="_blank" rel="noopener noreferrer"}
