---
title: "How to use BioHUG"
format: html
---


::: {.callout collapse="true"}
### Can you prioritise samples from patients in my research study ?

Yes. If the patients in your research study have signed the general consent, and not subsequently withdrawn that consent, we can prioritise them for DNA extraction. Bear in mind that the DNA banking step relies on a patient having a separate blood test as part of their routine care.
:::

::: {.callout collapse="true"}
### Will I need additional ethical approval to use BioHUG ?

Yes. You will need to apply for ethical approval for your study. BioHUG can do two things to help 1. Help design your study. For example if you wish to start with patients who already have a banked DNA sample, or genome wide association data, we can provide meta data (for example summaries of numbers of patients) 2. If you have a group of patients in your study and you wish to reuse genetic data from those who are already in BioHUG.
:::

::: {.callout collapse="true"}
### Can I collect more than one sample from the same patient ?

Yes if you let us know we can prioritise collection of 2 or more samples from the same patient. We do this securely in the HUG system, but you need to inform us because the default is to only collect one DNA sample per patient.
:::


::: {.callout collapse="true"}
### Are samples other than DNA available ?

As of March 2026, no. Since beginning DNA biobanking in February 2025, BioHUG has collected only DNA samples. However, it may be possible later in 2026 or 2027 to bank serum and plasma samples.
:::

::: {.callout collapse="true"}
### How much does it cost ?

Nothing for DNA banking. There is no cost to researchers to bank DNA. Funding is in place to extract DNA from 20,000 HUG patients who have signed the general consent. This initial collection will be complete in early 2027. We will also have genome wide genetic data, from the GSAMD illumina array available from 5000 in summer 2026. In the interests of data security the individual level data will only be available to a limited set of trained researchers. We will be able to provide summary level data at no cost.

Genetic data on additional samples, and banking of serum and plasma is subject to further funding, but we will be able to do this in a very cost efficient way. For more information please contact the PI of the study Prof. Timothy Frayling at timothy.frayling\@unige.ch
:::

::: {.callout collapse="true"}
### Is BioHUG accredited with the Swiss Biobanking platform ?

Yes. BioHUG has Swiss Biobanking Platform accreditation. More details [here](https://swissbiobanking.ch/sbp-directory/){target="_blank" rel="noopener noreferrer"}.
:::


::: {.callout collapse="true"}
### What are the inclusion and exclustion criteria for BioHUG ?

BioHUG consists of adult HUG patients who have signed the general consent as and adult at any point since 2017, not subsequently withdrawn that consent, and have had a routine blood test since February 2025.
:::

::: {.callout collapse="true"}
### How representative is BioHUG ?

BioHUG is very representative of the background Geneva population. No new blood sample or research questions or tests are performed. This lowers the barriers to participation. We estimate that 25% of participants are of non-European genetic ancestry.
:::

