---
title: "Qu'est-ce que BioHUG ? "
editor: visual
editor_options: 
  chunk_output_type: console
---

BioHUG est la collection, ou « banque », d’échantillons humains (notamment ceux comprenant de l’ADN) dé-identifiés de l’Hôpital universitaire de Genève (voir ci-dessous pour plus de détails sur la dé-identification/pseudo-anonymisation). Ils proviennent de patients ayant signé le [consentement general](https://www.hug.ch/aider-recherche){target="_blank" rel="noopener noreferrer"} et ainsi autorisé les chercheurs à utiliser leurs données médicales et leurs échantillons anonymisés à des fins de recherche. A tout moment, **les patients peuvent revenir sur leur décision en contactant** : \<aider-la-recherche\@hcuge.ch\> or telephone: 022 372 91 57. Vous trouverez plus d’informations sur la brochure de consentement [ici](https://www.hug.ch/aider-recherche){target="_blank" rel="noopener noreferrer"} ou grâce à cette vidéo [ici](https://www.youtube.com/watch?v=Cze2w8w6XUw){target="_blank" rel="noopener noreferrer"}, et pouvez télécharger la déclaration de consentement [ici](https://www.hug.ch/sites/interhug/files/structures/aider_la_recherche/declaration-consentement-aider-la-recherche.pdf){target="_blank" rel="noopener noreferrer"}.

### Pourquoi BioHUG collecte-t-il de l'ADN ?

L’ADN est présent dans presque toutes les cellules du corps humain et sert de plan directeur déterminant la structure et le fonctionnement de l’organisme. De minuscules variations de l’ADN hérité des parents influencent la couleur des cheveux et desyeux, la taille et lepoids, le risque de développer certaines maladies, ainsi que la capacité à répondre à des traitements. Pour en savoir plus, cliquer [ici](https://www.mongenome.ch/fr/){target="_blank" rel="noopener noreferrer"}

Les chercheurs utilisent des échantillons d’ADN pour comprendre pourquoi certaines maladies affectent certaines personnes ou pourquoi un médicament est plus efficace chez certaines personnes que chez d’autres. Cette approche de la compréhension des maladies, qui repose sur des données humaines et des échantillons d’ADN, est extrêmement importante pour la recherche médicale et est largement utilisée à travers le monde pour rechercher de nouveaux traitements et réduire les effets secondaires potentiels.

### Comment fonctionne BioHUG ?

Lors d’une prise de sang de routine, par exemple pour contrôler votre taux de cholestérol ou l’état de vos reins, il reste souvent un peu de sang qui n’est pas utilisé pour l’analyse. Ce sang non utilisé est généralement jeté et détruit, au bout de quelques jours. Dans le cadre de BioHUG, nous collectons ces résidus d’échantillons sanguins provenant de personnes ayant signé le consentement général, puis nous en extrayons l’ADN dans les laboratoires des HUG.

Début 2026, plus de 150 000 genevois avaient déjà signé le consentement général autorisant la réutilisation de leurs données médicales et de leurs échantillons à des fins de recherche. BioHUG vise à constituer une banque d’ADN provenant de 20 000 de ces personnes d’ici début 2027, ce qui fera de BioHUG le plus grand projet de recherche biomédicale à Genève et l’un des plus importants en Europe mené par un hôpital.

### Quels sont les objectifs de BioHUG ?

BioHUG n’est pas un projet de recherche spécifique. Son objectif est plutôt de poser les bases de nouveaux projets de recherche, pouvant porter sur de nombreuses maladies et des réponses aux traitements. Les projets de recherche consisteront généralement à croiser des données génétiques avec des données médicales afin de mieux comprendre certaines maladies. [CALIBRATE](../study_calibrate.qmd) est l’un des premiers projets de recherche issus de BioHUG.

### Comment puis-je m'inscrire à BioHUG ?

Il n’est pas nécessaire de vous inscrire à une étude si vous avez déjà signé le formulaire de consentement général. Cela signifie qu’aucun nouveau prélèvement sanguin ni aucune nouvelle information ne sont requis. Si vous souhaitez que vos échantillons soient intégrés à BioHUG et que vous n'avez pas encore signé le formulaire de consentement général, veuillez suivre les instructions fournies [ici](https://www.hug.ch/aider-recherche){target="_blank" rel="noopener noreferrer"}

### Quels sont les avantages pour les patients ?

Il n’y a pas d’avantage direct immédiat pour les patients individuels. Participer à BioHUG, c’est contribuer à la découverte de nouveaux liens entre les gènes et les maladies. Ces nouveaux liens peuvent ensuite être vérifiés dans le cadre d’études distinctes. D’autres hôpitaux à travers le monde disposent de banques d’ADN très similaires, regroupant des échantillons provenant de dizaines de milliers de patients utilisés pour faire des découvertes importantes . Par exemple, une étude récente utilisant plusieurs « banques » d’ADN similaires a mis en évidence un lien entre des mutations d’un certain gène et des diagnostics erronés de diabète. En savoir plus sur cette étude, cliquer [ici](https://www.ukbiobank.ac.uk/research-stories/hidden-genetic-condition-means-many-black-men-get-diabetes-diagnoses-too-late/){target="_blank" rel="noopener noreferrer"}.

Pour plus d'informations, consultez la page [Questions Fréquemment Posées](faqs.qmd)
